// Searchable business-type options. Broad global coverage with strong
// Nigerian/African informal-economy representation. Used by a type-ahead input.

export const BUSINESS_TYPES: string[] = [
  // Retail / provisions
  "Provisions Store / Kiosk",
  "Supermarket",
  "Mini Mart",
  "Open Market Stall",
  "Foodstuff Seller",
  "Frozen Foods (Cold Room)",
  "Drinks & Beverages Distributor",
  "Bakery",
  "Confectionery / Snacks",
  "Fruits & Vegetables Seller",
  "Meat / Abattoir / Butcher",
  "Fish Seller",
  "Grains & Cereals Dealer",
  // Pharmacy / health
  "Pharmacy / Chemist",
  "Patent Medicine Store",
  "Herbal / Traditional Medicine",
  "Hospital / Clinic",
  "Optical / Eye Care",
  "Dental Clinic",
  "Laboratory / Diagnostics",
  // Fashion / beauty
  "Boutique / Clothing",
  "Tailoring / Fashion Design",
  "Fabrics (Ankara / Lace) Dealer",
  "Shoes & Bags",
  "Jewellery / Accessories",
  "Cosmetics & Beauty Products",
  "Hair Salon / Barbing",
  "Spa / Beauty Salon",
  "Makeup Artistry",
  // Phones / electronics / tech
  "Phone & Accessories",
  "Phone Repair",
  "Computer / Laptop Sales",
  "Electronics Store",
  "Electrical Appliances",
  "Computer / Business Center",
  "Software / Tech Startup",
  "Internet / Cyber Cafe",
  // Building / hardware
  "Building Materials",
  "Hardware Store",
  "Cement & Blocks",
  "Paint Store",
  "Plumbing Materials",
  "Electrical Materials",
  "Furniture Maker / Seller",
  "Aluminium / Glass Works",
  // Auto / transport
  "Auto Spare Parts",
  "Mechanic Workshop",
  "Car Sales / Dealership",
  "Car Wash",
  "Vulcanizer / Tyre Services",
  "Motorcycle / Okada Parts",
  "Logistics / Dispatch / Delivery",
  "Transport / Haulage",
  // Food service
  "Restaurant / Bukka",
  "Fast Food",
  "Catering Services",
  "Bar / Lounge",
  "Hotel / Guest House",
  "Event Center",
  "Pure Water / Sachet Water Production",
  // Financial / professional services
  "POS / Agent Banking",
  "Bureau De Change",
  "Microfinance / Cooperative",
  "Accounting / Bookkeeping",
  "Legal Services",
  "Real Estate / Property",
  "Insurance Services",
  "Consulting",
  // Agriculture
  "Poultry Farm",
  "Fish Farm",
  "Crop Farming",
  "Livestock Farming",
  "Agro-Allied / Farm Inputs",
  "Feed & Veterinary Supplies",
  // Manufacturing / production
  "Manufacturing",
  "Sachet / Bottled Water Factory",
  "Block Industry",
  "Furniture Production",
  "Soap / Detergent Production",
  "Printing Press",
  // Services
  "Laundry / Dry Cleaning",
  "Photography / Videography",
  "Printing & Branding",
  "Dry Cleaning",
  "School / Education",
  "Lesson / Training Center",
  "Gym / Fitness",
  "Security Services",
  "Cleaning Services",
  "Generator Sales & Repair",
  "Solar / Inverter Installation",
  "Interior Decoration",
  "Rentals (Chairs, Canopies)",
  // General / wholesale / import
  "Wholesale / Distribution",
  "Importation / Trading",
  "General Merchandise",
  "Online Store / E-commerce",
  "Dropshipping",
  "Gift Store",
  "Bookshop / Stationery",
  "Toys & Baby Products",
  "Pet Shop / Pet Supplies",
  "Agriculture Produce Export",
  "Other",
];
